name: Pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-go:
    name: Lint Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: "./go.mod"
          cache: false
      - name: Install
        run: |
          go install github.com/gordonklaus/ineffassign@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/kisielk/errcheck@latest
          go install go.uber.org/nilaway/cmd/nilaway@latest
      - name: format
        if: always()
        run: test -z $(gofmt -l ./.. | grep -v vendor)
      - name: vet
        if: always()
        run: go vet ./...
      - name: errcheck
        if: always()
        run: errcheck ./...
      - name: ineffassign
        if: always()
        run: ineffassign ./...
      - name: staticcheck
        if: always()
        run: staticcheck ./...
      - name: nilaway
        if: always()
        run: nilaway ./...

  test-go:
    name: Test Go
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: test
        run: go test ./...

  lint-svelte:
    name: Lint Svelte
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: "./.nvmrc"

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Build
        run: make build
        working-directory: .

      - name: Prettier and ESLint
        run: npm run lint
        working-directory: ./ui
        if: always()

      - name: svelte-check
        run: npm run check
        working-directory: ./ui
        if: always()

  test-e2e-firefox:
    name: Test E2E (Firefox)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: "./.nvmrc"

      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Setup caddy
        run: |
          curl -LO "https://github.com/caddyserver/caddy/releases/download/v2.10.2/caddy_2.10.2_linux_amd64.tar.gz"
          tar -xzf caddy_2.10.2_linux_amd64.tar.gz
          sudo mv caddy /usr/local/bin/
          sudo chmod +x /usr/local/bin/caddy

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Install Playwright dependencies
        working-directory: ./e2e
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Build
        run: make build-e2e
        working-directory: .

      - name: Run Playwright tests
        run: npx playwright test --project=firefox
        working-directory: ./e2e

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-firefox
          path: e2e/playwright-report/
          retention-days: 30

  test-e2e-chrome:
    name: Test E2E (Chrome)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: "./.nvmrc"

      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Setup caddy
        run: |
          curl -LO "https://github.com/caddyserver/caddy/releases/download/v2.10.2/caddy_2.10.2_linux_amd64.tar.gz"
          tar -xzf caddy_2.10.2_linux_amd64.tar.gz
          sudo mv caddy /usr/local/bin/
          sudo chmod +x /usr/local/bin/caddy

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Install Playwright dependencies
        working-directory: ./e2e
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Build
        run: make build-e2e
        working-directory: .

      - name: Run Playwright tests
        run: npx playwright test --project=chromium
        working-directory: ./e2e

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-chrome
          path: e2e/playwright-report/
          retention-days: 30

  test-e2e-macos:
    name: Test E2E (Safari)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: "./.nvmrc"

      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version-file: "./go.mod"
          cache: false

      - name: Setup caddy
        run: |
          curl -LO "https://github.com/caddyserver/caddy/releases/download/v2.10.2/caddy_2.10.2_mac_arm64.tar.gz"
          tar -xzf caddy_2.10.2_mac_arm64.tar.gz
          sudo mv caddy /usr/local/bin/
          sudo chmod +x /usr/local/bin/caddy

      - name: Install dependencies
        run: npm install
        working-directory: ./ui

      - name: Install Playwright dependencies
        working-directory: ./e2e
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Build
        run: make build-e2e
        working-directory: .

      - name: Run Playwright tests
        run: npx playwright test --project=webkit
        working-directory: ./e2e

      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-safari
          path: e2e/playwright-report/
          retention-days: 30

